### ISSUE TITLE
Proper model and resource promise parallelization for v1.0.0

### ISSUE THREAD

**Issue by dylnslck** [dcslack/restle#2]
There are some drawbacks with the current promise parallelization proposal:

``` js
app.model('user', 'pets').each(
  user => user.findResource('1'),
  pets => pets.find()
).then(results =>
  return results.user.put('pets', results.pets);
).then(user => {
  // Resource
});
```

This is deceivingly verbose because it incorrectly implies that there is a model named `pets`. Really,
the model would be named `animal`. Correcting it produces the following example:

``` js
app.model('user', 'animal').each(
  user => user.findResource('1'),
  animal => animal.find()
).then(results =>
  return results.user.put('pets', results.animal);
).then(user => {
  // Resource
});
```

This is much less verbose and even a little confusing because at first glance it seems that it is adding a single animal to an array of pets. This proposal also requires that one gets the order of the `.each` arguments correctly. The order shouldn't matter.

I propose the following:

``` js
app.model('user', 'animal:pets').each({
  user(model) {
    // model === app.model('user')
    return model.findResource('1');
  },

  pets(model) {
    // model === app.model('animal')
    return model.find({
      page: { offset: 20, limit: 40 },
      filter: { age: 5 },
    });
  },
}).then(results => {
  const user = results.user; // Resource
  const pets = results.pets; // ResourceArray

  return results.user.put('pets', pets);
}).then(user => {
  // Resource
});
```

In the `.model` arguments, you can use a colon to map a model to a more verbose key. The `.each` method would take in an object rather than multiple arguments, so the order doesn't matter. Each method in `.each` will be supplied with the proper model.

**Comment by dylnslck** [comment]
A `map` method is a more appropriate name than `each`:

``` js
app.model('user', 'animal:pets').map({
  user(model) {
    // model === app.model('user')
    return model.findResource('1');
  },

  pets(model) {
    // model === app.model('animal')
    return model.find({
      page: { offset: 20, limit: 40 },
      filter: { age: 5 },
    });
  },
}).then(results => {
  const user = results.user; // Resource
  const pets = results.pets; // ResourceArray

  return results.user.put('pets', pets);
}).then(user => {
  // Resource
});
```

**Comment by migueloller** [comment]
:+1:
